---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  annotations:
    test: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        test: still-a-test

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    test: stil-only-a-test